# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - schnoodle

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REACT_APP_FARMING_START_BLOCK: 13761101
  REACT_APP_BSC_EXPLORER_URL: https://bscscan.com
  REACT_APP_BSC_NET_ID: 56
  REACT_APP_BSC_NET_NAME: BSC Mainnet
  REACT_APP_BSC_RPC_URL: https://bsc-dataseed.binance.org/
  REACT_APP_ETH_EXPLORER_URL: https://etherscan.io
  REACT_APP_ETH_NET_ID: 1
  REACT_APP_ETH_NET_NAME: Ethereum Mainnet
  REACT_APP_ETH_RPC_URL: https://mainnet.infura.io/v3/
  REACT_APP_SERVER_URL: https://server.schnoodle.finance

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'schnoodle'
          slot-name: 'test'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_110ACB2DD2B148EF8ED187EDAF0A1914 }}
          package: .
